#!/usr/bin/env bash
# Script to give specified information about the server subdomains

check_domain() {
  local domain="$1"
  local subdomain="$2"
  local subdomains=("www" "lb-01" "web-01" "web-02")
  local sub  # Define sub outside the loop

  # Validate input as required
  if [ -z "$domain" ]; then
    echo "Error: Domain name not provided."
    exit 1
  fi

  if [ -z "$subdomain" ]; then
    # No subdomain being specified, do all
    for sub in "${subdomains[@]}"; do
      query_domain="$sub.$domain"
      result=$(dig "$query_domain" +short)
      record_type=$(echo "$result" | awk '{print $2}')
      destination=$(echo "$result")

      echo "The subdomain $sub is a $record_type record and points to $destination"
    done
  else
    # Subdomain being specified
    query_domain="$subdomain.$domain"
    result=$(dig "$query_domain" +short)
    record_type=$(echo "$result" | awk '{print $2}')
    destination=$(echo "$result")

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
  fi
}

check_domain "$1" "$2"

