#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=2.4.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend dwincreatives.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 267216-web-01 54.172.220.145
        server 267216-web-02 34.229.56.193
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
