#!/usr/bin/env bash
# This script prints a list of the current running processes
# Must show all processes, for all users, including those which might not have a TTY
# Display a user-oriented format
# Show process hierarchy

ps -axuf
