#!/usr/bin/env bash
# This script displays "Best School" ten times, then "Hi" on nineth count

count=0
while [ $count -lt 10 ]
do
    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    ((count++))
done
