#!/usr/bin/env bash
# This script prints files in current directory in list format
# With only the part of the name after the first of the dash displayed
for fl in $( ls ):
do
	echo "$fl" | cut -d "-" -f 2- | rev | cut -d ":" -f 2- | rev
done
